name: Build and Test

on: # Trigger the workflow on push or pull request to the main branch or any feature branch
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs every 5 minutes at sunday
    - cron: "*/5 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps: # Define the steps to build the project
      - name: Checkout code
        uses: actions/checkout@v4 # Check out the code from the repository

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/ 
  test:
    needs: build # This job depends on the build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: npm test
  deploy:
    if: github.ref == 'refs/heads/main' # Only run this job on the main branch
    needs: [build, test] # Waits for multiple jobs # This job depends on the test & build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "Deploying to production..." # Replace with actual deployment commands

